### ISSUE TITLE
Read Authenticator keys from a file

### ISSUE THREAD

**Issue by syedibrahim** [syedibrahim/GAuthy#5]
### What

1. Option to read authenticator keys from a file and display TOTP

2. Option to store new authenticator key passed as argument or QR image to a file
### To-do

- [ ] Read Name/Label and Authenticator Key from file
- [ ] Display TOTP for each Key in file
- [ ] Display TOTP for requested key name/label from file
- [ ] Update readme

**Comment by dbowd** [comment]
hi, can you assign this issue to me? :)
